language: php

addons:
  apt:
    packages:
    - parallel

cache:
  directories:
  - vendor
  - $HOME/.composer/cache
  - $HOME/.sonar/cache

before_install:
- phpenv config-rm xdebug.ini

install:
- composer install

script:
- >
  echo;
  echo "Validating the composer.json";
  composer validate --no-check-all --no-check-lock --strict;

- >
  echo;
  echo "Linting all PHP files";
  composer ci:php:lint;

- >
  echo;
  echo "Running the unit tests";
  composer ci:tests:unit;

#- >
#  echo;
#  echo "Running the integration tests";
#  composer ci:tests:integration;

jobs:
  fast_finish: true
  include:
  #    - stage: test
  #      php: 7.2
  #      env: TYPO3=dev-master
  #    - stage: test
  #      php: 7.2
  #      env: TYPO3=^9.0
  #    - stage: test
  #      php: 7.1
  #      env: TYPO3=^8.7
      - stage: test
        php: 7.0
  #    - stage: test
  #      php: 5.6
  #      env: TYPO3=^7.6
  - stage: test
    php: 5.6
  #    - stage: test
  #      php: 5.5
  #      env: TYPO3=^7.6

  #    - stage: 🚢 to ter
  #      if: tag IS present AND env(TYPO3_ORG_USERNAME) IS present AND env(TYPO3_ORG_PASSWORD) IS present
  #      php: 7.0
  #      env: TYPO3=^8.7
  #      before_install: skip
  #      install: skip
  #      before_script: skip
  #      script:
  #      - >
  #        echo;
  #        echo "Preparing upload of release ${TRAVIS_TAG} to TER";
  #        echo;
  #        echo;
  #        composer require --dev nimut/typo3-complete:$TYPO3;
  #        composer require --update-no-dev helhum/ter-client:dev-master;
  #
  #        # Cleanup before we upload
  #        git reset --hard HEAD && git clean -fx;
  #
  #        # Upload
  #        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
  #        echo;
  #        echo "Uploading release ${TRAVIS_TAG} to TER";
  #        echo;
  #        echo;
  #        .Build/bin/ter-client upload tablecleaner . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE";

